apiVersion: apps/v1
kind: Deployment
metadata:
  name: updateservice-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: updateservice-operator
      control-plane: updateservice-operator
  template:
    metadata:
      labels:
        name: updateservice-operator
        control-plane: updateservice-operator
    spec:
      serviceAccountName: updateservice-operator
      containers:
        - name: updateservice-operator
          image: controller:latest
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "updateservice-operator"
            - name: RELATED_IMAGE_OPERAND
              value: "quay.io/cincinnati/cincinnati:latest"
