apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: updateservice-operator
  name: updateservice-operator-metrics
spec:
  ports:
  - name: metrics
    port: 80
    targetPort: 8080
  selector:
    control-plane: updateservice-operator
status:
  loadBalancer: {}
