apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: updateservice-operator
  name: updateservice-operator-metrics
  namespace: openshift-updateservice
spec:
  ports:
  - name: metrics
    port: 80
    targetPort: 8080
  selector:
    control-plane: updateservice-operator
